management:
  endpoints:
    web:
      exposure:
        include:
        - "health"
        - "metrics"
        - "info"
server:
  port: 8001

store:
  category-service-host: http://localhost:8002

---

spring:
  profiles: production
  data:
    mongodb:
      host: invinvible-starfish-mongodb
      database: product-service

server:
  port: 8000
store:
  category-service-host: http://category-service